### ISSUE TITLE
MacOs上使用响应体乱码

### ISSUE THREAD

**Issue by anlen123** [fffguo/utools-curl#13]
MacOs上使用响应体乱码

**Comment by fffguo** [comment]
方便给下curl，和乱码前的响应体吗？

**Comment by anlen123** [comment]
随便一个api，这里就随便找了一个，返回是json的。
https://restapi.amap.com/v3/weather/weatherInfo?parameters=成都
<img width="936" alt="image" src="https://user-images.githubusercontent.com/49887895/177285051-191d711f-2cf4-48ca-b59f-6c8673b60609.png">

**Comment by fffguo** [comment]
![image](https://user-images.githubusercontent.com/27751972/177285373-8de6d743-07e8-4397-ba0a-cac8e85f3ebe.png)
神奇的bug，我来看看原因

**Comment by fffguo** [comment]
![image](https://user-images.githubusercontent.com/27751972/177285373-8de6d743-07e8-4397-ba0a-cac8e85f3ebe.png)
神奇的bug，我来看看原因

**Comment by anlen123** [comment]
问题不大，反正确实有这个问题，不知道是不是只有我这。

**Comment by fffguo** [comment]
> 问题不大，反正确实有这个问题，不知道是不是只有我这。

很抱歉，最近有些忙，才刚看这个问题。

我在朋友的mac电脑上，也没有复现这个问题，再次确认下是所有的curl命令返回结果都乱码吗？

**Comment by anlen123** [comment]
那没办法了，没关系。

**Comment by fffguo** [comment]
> 那没办法了，没关系。

你好，关于这个问题我这边有个解决的思路，但是没有能复现的设备，可以加微信帮我试下吗？
我的微信： l595726017

**Comment by fffguo** [comment]
> 那没办法了，没关系。

**Comment by fffguo** [comment]
问题原因：
以springboot项目为例，服务器配置开启压缩，可以计算换取带宽，压缩返回报文
server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json

请求头带有：Accept-Encoding: gzip, deflate，标识客户端支持的压缩方式为：gzip, deflate
返回头带有：Content-Encoding: gzip，标识此次返回的body体经过gzip压缩

客户端需要根据返回头的gzip解压内容，如不处理，拿到gzip压缩后的数据必然会乱码

新版本已提交utools审核，预计最迟明日会发布到商店中
