### ISSUE TITLE
插件入口做下限制

### ISSUE THREAD

**Issue by itldg** [fffguo/utools-curl#18]
现在无论输入什么内容，curl都会出现在列表中

可以做下限制，仅框中的内容为网址或者curl格式内容时才出现插件

**Comment by itldg** [comment]
```
      "cmds": [
        {
          "type": "regex",
          "match": "/^(https?:\/\/|curl )/ig",
          "label": "curl"
        }
      ]
```

我这样做了之后似乎会一次有一次没

**Comment by fffguo** [comment]
我也复现了这个奇怪的问题

**Comment by itldg** [comment]
> 我也复现了这个奇怪的问题

这个其实还是有必要的,不然插件出现的太频繁了

**Comment by fffguo** [comment]
先保持不变吧，我去咨询下utool的官方，看看有什么办法没，看着这个问题像是官方有bug的感觉

**Comment by fffguo** [comment]
/^(https?://|curl)/i

去掉全局匹配就行了
官方回复：匹配时间超过15毫秒会丢弃

**Comment by fffguo** [comment]
新包我发布在github上了，你可以下载拖动到utools上进行安装，商店需要官方审核预计会迟一两天

感谢你的代码(*￣︶￣)

**Comment by itldg** [comment]
ok，我下载看看
