### ISSUE TITLE
post数组数据错误

### ISSUE THREAD

**Issue by itldg** [fffguo/utools-curl#20]
POST请求数据为
```
permissions[]: 91
permissions[]: 94
```

用curl插件发出请求不成功

浏览器复制curl
```
...
--data-raw 'permissions%5B%5D=91&permissions%5B%5D=94' \
...
```

curl复制cur结果
```
...
--data 'permissions%5B%5D=91&permissions%5B%5D=94'
...
```

和这个有关系么？我不太会抓这个插件的包，不知道怎么分析了

**Comment by fffguo** [comment]
--data 与 --data-raw  不影响使用，curl命令都能解析，

主要原因还是使用的一个开源项目会把body体内容解析成  --data   ，而copy浏览器curl是--data-raw

**Comment by fffguo** [comment]
-d,--data key=value
value如果是@a_file_name，表示数据来自一个文件，文件中的回车符和换行符将被转换

 --data-raw key=value
@也作为普通字符串，不会作为文件名给出文件名的标志。即value如果是@file_name，只表示值为“@file_name”的字符串。
其他等价于-d

**Comment by itldg** [comment]
> --data 与 --data-raw 不影响使用，curl命令都能解析，
> 
> 主要原因还是使用的一个开源项目会把body体内容解析成 --data ，而copy浏览器curl是--data-raw

嗯，那就剩下提交问题了，同一个curl格式文本，放在apifox和curl插件的结果如下

![image](https://user-images.githubusercontent.com/13432299/185566796-fb1bff01-e185-43a5-a4e2-3692f4a0d093.png)

![image](https://user-images.githubusercontent.com/13432299/185566873-f966f1bf-e4cb-4f5b-b533-93a184b6a64d.png)

**Comment by fffguo** [comment]
方便贴下原始curl吗

**Comment by itldg** [comment]
```
curl 'http://mgj.demo.com/api/v1/user/role' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Authorization: Bearer UmpTD8pIMla3ocu1d2tg8HoXi2UCMv0KIhvM8lPUZKxbVhzAKymi4kS2xfCA' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: laravel_session=zJvgaqqkP7Ga6BAU5CJTQli7cmgnIuCNFHgQJRcz' \
  -H 'Origin: http://mgj.demo.com' \
  -H 'Referer: http://mgj.demo.com/manage/system/user' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' \
  -H 'X-CSRF-TOKEN: ekSDUCfPtWXkJjRDcuJwvzKizDXEyuIoQ9UxxAi7' \
  -H 'X-Requested-With: XMLHttpRequest' \
  --data-raw 'user_id=10187&roles%5B%5D=13&roles%5B%5D=9' \
  --compressed \
  --insecure
```
那咋会不方便呢

**Comment by wanglong126** [comment]
加你微信没搜到

**Comment by fffguo** [comment]
> 方便贴下原始curl吗

搜我手机号呢   18912950023

**Comment by itldg** [comment]
> > 方便贴下原始curl吗
> 
> 搜我手机号呢 18912950023

加了

**Comment by fffguo** [comment]
header头使用application/x-www-form-urlencoded时，需传入Content-Length，不然后端无法获取body中值

**Comment by itldg** [comment]
问题已解决，结帖
